apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: wil-playground
  namespace: dev
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: wil-playground
  template: 
    metadata: 
      labels: 
        app: wil-playground
    spec: 
      containers: 
        - name: wil-playground
          image: wil42/playground:v1
          ports: 
            - containerPort: 8888
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: wil-playground-service 
  namespace: dev 
spec: 
  selector: 
    app: wil-playground 
  ports: 
    - protocol: TCP 
      port: 8888
      targetPort: 8888

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wil-playground-ingress
  namespace: dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web 
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: wil-playground-service
                port:
                  number: 8888
