apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: redacted
  namespace: dev
  annotations:
    display-name: "*redacted*" 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: redacted 
  template: 
    metadata: 
      labels: 
        app: redacted 
    spec: 
      containers: 
        - name: redacted
          image: wil42/playground:v1 
          ports: 
            - containerPort: 8880
--- 

apiVersion: v1 
kind: Service 
metadata: 
  name: redacted-service 
  namespace: dev 
spec: 
  selector: 
    app: redacted 
  ports: 
    - protocol: TCP 
      port: 8888
      targetPort: 8880
      nodePort: 30007
